export const data = {
  title: 'Todos son mis hijos: detrás del guión como marioneteros invisibles',
  subtitle: '',
  content: `Son las once de la mañana y estoy frente a la computadora leyendo una página llamada Mundo bebe. Me abro paso entre fotos de querubines regordetes, chupetes animados con música y videos informativos sobre el puerperio, y repaso la última lista de nombres del día: Miguel Ángel: del hebreo, quiere decir Dios es justo; Juan Carlos: también del hebreo Yohanam, Dios es misericordioso; Alí: del árabe, el que es sublime; Santiago: del hebreo Sant Yago y significa suplantador; Nicolás: viene del griego Niké, que significa victoria, y Matías: otra vez del hebreo Mattith-Yah y significa don de Dios.

Dejo de leer y pienso algunos segundos. ¿Lo veo como un Matías? ¿Me imagino a una chica diciendo: Matías, no puedo dejar de pensar en vos o Ya vas a ver cuando se entere Matías de esto? No suena mal, es lindo y simple. Tiene fuerza si el apellido es robusto. Lo anoto. Nicolás no, ya lo vi demasiado. Juan Carlos es para alguien más grande, tampoco va. Alí es muy raro. No me gustan los nombres raros, suenan falsos.

Vuelvo a la lista y retomo, pero ahora en orden alfabético. Arnaldo. Amancio. Alfonso. Antonio. Abelardo. Amadeo. Antonio. Adolfo. Athos. Ninguno me cierra demasiado y creo que ya leí todos los que hay. Mejor parar y pensar. Mientras me tomo un recreo, llega Guillermo, mi asistente, encuentra la página abierta en la computadora y se sorprende. "¡La página de bebes!" me dice, emocionado. Asiento, entre contenta y agotada, y le confirmo la noticia. ¿Para qué ocultarlo si ya la vio? Es verdad. Estamos escribiendo un programa nuevo.

Lo primero que hacemos cuando arrancamos un programa de televisión es un capítulo piloto en el que además de abrir todas las líneas de la trama, presentamos a los personajes. Con más o menos escenas tratamos de que aparezcan todos: los ricos, los pobres, los buenos, los villanos, los ayudantes de los protagonistas, los que harán las líneas de humor. Eso incluye elegir el nombre y apellido de todos, como si hubiesen nacido ese día. Para eso, no usamos otra cosa más que páginas y libros con nombres de bebes, que a simple vista es algo raro, pero que a la vez no deja de ser lógico. Como padres ilusionados, nosotros también pensamos el nombre para una persona que está por llegar al mundo.

Los guionistas, además de elegir un nombre que nos guste (vamos a usarlo todo el año, lo tipearemos cien veces por día, lo escucharemos todas las noches) tenemos el compromiso de pensar en que sea atractivo y verosímil para el espectador. Queremos contar el origen de nuestros personajes, darle valor narrativo a esa elección: ¿Es de una familia trabajadora? Probablemente elijamos un apellido italiano o español. ¿Es de clase alta, de una familia tradicional? Uno patricio, quizá doble, que nos hayamos cruzado en algún libro de historia de casualidad. ¿Sus padres son personas frívolas y coquetas? Seguramente buscaremos qué nombres estaban de moda el año en que nació. ¿Padres sacrificados y trabajadores? Nombres de los padres de sus padres o de personajes de televisión. ¿Lo criaron los abuelos? Nombres de santos, nombres compuestos con María o Juan. Y además de que sea fuerte, que sea recordable, que nos resulte posible como un héroe o el galán de una gran historia de amor.

Yo, además, tengo algunas reglas personales para nombrar personajes. La primera es no caer en el lugar común de la rareza. Es común ver escritores llamados Susana Trocero o Jorge Manfrotto ponerle a sus personajes de ficción todos los nombres excéntricos y pintorescos que la vida real les negó. Eligen Yvette Rothschild o Mía Brisson en vez de María Marta González o Mónica Yañez porque piensan que lo extranjero o complicado es distinguido cuando en realidad sólo es falso e infantil. Construir particularidades poniendo un nombre raro es un atajo mentiroso y haragán. Lo que hace inolvidable a un personaje es que conmueva, no que sea inverosímil. Uno recuerda a Rolando Rivas por las ganas que tenía de su historia de amor se concretara, no porque Rivas fuese el único Rivas de Buenos Aires. La primera ficción que escribí, Ciega a citas, tenía una heroína llamada Lucía González. Me hice pasar por ella en un blog durante meses y cuando me preguntaban si yo era la autora real del blog, siempre respondía lo mismo: me llamo Carolina Aguirre, si creara un nombre de ficción, habiendo tanto para elegir. ¿A vos te parece que usaría Gonzalez de apellido? Me pondría algo mejor. Y con esa excusa, todos creyeron en mi engaño durante dos años y medio.

Otro vicio de los autores es hacer chistes privados o tratar de ser ingeniosos nombrando a los personajes como un amigo suyo o con variaciones de sus propios nombres. Las iniciales, las mismas letras, sus nombres al revés son torpezas narcisistas a las que les huyo un poco porque me da vergüenza, pero también porque el ingenio y los juegos de palabras además de ser tontos vuelven falso todo lo que está a su alrededor. Los guionistas tenemos que estar detrás del guión como marioneteros invisibles. Nuestra ambición es emocionar, no ser emocionantes. La historia es acerca de los protagonistas, todo lo que implique que nosotros aparezcamos, aunque sea lateralmente en la trama, sólo hace ruido, confunde y roba atención.

En Guapas aplicamos esta ley a rajatabla. Ninguna de las protagonistas se llama Mía, ni Tatum o Fiona. Elegimos nombres nobles que las vuelvan posibles y que nos ofrezcan diálogos sencillos y sensibles. Laura y Andrea Luna para las dos hermanas de clase media que se peleaban. Mónica Duarte, la más grande, y Natalia Diez para su hija. María Emilia García del Río la de clase alta venida a menos, Lorena Patricia Giménez la de clase baja con aspiraciones de recibirse de médica algun día. Con los hombres hicimos lo mismo. Mario Manfredi para el italiano, Rubén Donofrio para el empleado sindicalista, Alejandro Rey para un abogado. En Farsantes, en cambio, heredé algunas cosas que no hubiera elegido como ponerle Pedro Beggio al lindo de la historia. Lo resolví evitando su apellido durante toda la tira que lejos de ser gracioso, arruinaba las escenas de amor. Si Guillermo hubiera dicho Te amo, Pedro Beggio (bello) en una escena, la escena sólo habría sido una burla y distanciado al espectador.

Yo sé que la gente puede decirme que la realidad no sigue estas reglas. Que tienen una prima que se llama Nepomucena, una ahijada de dos años que se llama Graciela o un albañil llamado Wolfang arreglándole el baño de casa, pero la vida no es la ficción y la verdad y la verosimilitud son primas lejanas que son parecidas, pero nunca idénticas. Como los hijos, a los personajes uno les pone un nombre que también es un deseo. Algo que los represente, que los interpele, que sea bonito y fuerte, que les de seguridad, pero sobre todo, que los haga sentir tan únicos e inolvidables como los sentimos nosotros, que los trajimos a este mundo con tanto amor.`
}
